"use client";
import { useCallback, useEffect, useState } from "react";
import type { MediaAssetType, MediaAssetWithUsage } from "@/types/media";
import { invitationTypes, type InvitationTypeSlug } from "@/lib/catalog-taxonomy";
type Asset = MediaAssetWithUsage & { url: string };
export function MediaLibrary() {
  const [assets, setAssets] = useState<Asset[]>([]); const [type, setType] = useState(""); const [query, setQuery] = useState(""); const [trash, setTrash] = useState(false); const [message, setMessage] = useState(""); const [product, setProduct] = useState<InvitationTypeSlug>("web-premium"); const [uploading, setUploading] = useState(false);
  const load = useCallback(async () => { const params = new URLSearchParams(); if (type) params.set("type", type); if (query) params.set("q", query); if (trash) params.set("trash", "1"); const response = await fetch(`/api/admin/media?${params}`); const payload = await response.json() as { assets?: Asset[]; error?: string }; if (response.ok) setAssets(payload.assets || []); else setMessage(payload.error || "No se pudo cargar la biblioteca."); }, [type, query, trash]);
  useEffect(() => { const timer = setTimeout(() => void load(), 150); return () => clearTimeout(timer); }, [load]);
  async function action(id: string, action: "trash" | "restore") { const response = await fetch("/api/admin/media", { method:"PATCH", headers:{"content-type":"application/json"}, body:JSON.stringify({id,action}) }); const payload = await response.json() as { error?:string }; setMessage(response.ok ? (action === "trash" ? "Recurso enviado a papelera." : "Recurso restaurado.") : payload.error || "No se pudo actualizar."); await load(); }
  async function upload(file?: File) { if (!file) return; setUploading(true); setMessage(""); const body=new FormData(); body.append("file",file); body.append("invitationType",product); const response=await fetch("/api/admin/site/media",{method:"POST",body}); const payload=await response.json() as {error?:string;deduplicated?:boolean}; setMessage(response.ok ? (payload.deduplicated ? "El archivo ya existía; se reutilizó el recurso." : "Archivo agregado a la biblioteca.") : payload.error || "No se pudo subir."); setUploading(false); if(response.ok) await load(); }
  return <section className="admin-panel admin-media-library"><div className="admin-media-library__upload"><select value={product} onChange={(event)=>setProduct(event.target.value as InvitationTypeSlug)}>{invitationTypes.map((item)=><option value={item.slug} key={item.slug}>{item.label}</option>)}</select><label className="button-secondary site-upload-button">{uploading ? "Subiendo…" : "Subir archivo para este producto"}<input type="file" disabled={uploading} accept=".jpg,.jpeg,.png,.webp,.avif,.svg,.pdf,.mp4,.webm" onChange={(event)=>void upload(event.target.files?.[0])} /></label></div><div className="admin-media-library__filters"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre" /><select value={type} onChange={(event) => setType(event.target.value)}><option value="">Todos los tipos</option>{(["image","video","pdf","svg","other"] as MediaAssetType[]).map((item) => <option key={item} value={item}>{item.toUpperCase()}</option>)}</select><label><input type="checkbox" checked={trash} onChange={(event) => setTrash(event.target.checked)} /> Mostrar papelera</label></div>{message ? <p className="muted">{message}</p> : null}<div className="admin-media-library__grid">{assets.map((asset) => <article key={asset.id}><div className="admin-media-library__preview">{["image","svg"].includes(asset.asset_type) ? <img src={asset.url} alt="" /> : asset.asset_type === "video" ? <video src={asset.url} muted preload="metadata" /> : <span>{asset.asset_type.toUpperCase()}</span>}</div><h2 title={asset.original_filename}>{asset.original_filename}</h2><p>{asset.mime_type} · {(asset.size_bytes / 1024 / 1024).toFixed(2)} MB</p><p>{new Date(asset.created_at).toLocaleDateString("es-MX")} · {asset.usage_count} usos</p>{asset.usages?.length ? <details><summary>Ver usos</summary><ul>{asset.usages.map((usage) => <li key={usage.id}>{usage.entity_type}: {usage.entity_id}<br /><small>{usage.field_name}</small></li>)}</ul></details> : null}<div className="admin-media-library__actions"><button type="button" onClick={() => void navigator.clipboard.writeText(asset.url)}>Copiar URL</button>{asset.deleted_at ? <button type="button" onClick={() => void action(asset.id,"restore")}>Restaurar</button> : <button type="button" disabled={asset.usage_count > 0} title={asset.usage_count ? "El recurso está en uso" : "Enviar a papelera"} onClick={() => void action(asset.id,"trash")}>Eliminar</button>}</div></article>)}</div></section>;
}
